
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jaedon
 */
public class LogIn extends javax.swing.JFrame
{

    /**
     * Creates new form LogIn
     */
    public LogIn()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        LoginB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        errorDisplay = new javax.swing.JTextArea();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 300, 400, 350));
        setMinimumSize(new java.awt.Dimension(400, 350));
        setPreferredSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Please enter phone number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        Phone.setText("E.g.82 911 1829");
        Phone.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                PhoneMouseClicked(evt);
            }
        });
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel2.setText("Please enter username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        Username.setText("E.g.JaedonA");
        Username.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                UsernameMouseClicked(evt);
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel3.setText("Please enter password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        Password.setText("jPasswordField1");
        Password.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                PasswordMouseClicked(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        LoginB.setText("Login");
        LoginB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LoginBActionPerformed(evt);
            }
        });
        getContentPane().add(LoginB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        errorDisplay.setColumns(20);
        errorDisplay.setRows(5);
        jScrollPane1.setViewportView(errorDisplay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 120, 190));

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Creating global obj
    LogInManager LMobj = new LogInManager();
    StartPage Spobj = new StartPage();
    
    //Creating global varaibles for user Input
    private static String UsernameOut;
    private static String PhoneOut;
    private static String PasswordOut;
    
    // Clears phone field on click
    private void PhoneMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_PhoneMouseClicked
    {//GEN-HEADEREND:event_PhoneMouseClicked
        Phone.setText("");
        errorDisplay.setVisible(false);
    }//GEN-LAST:event_PhoneMouseClicked
    // Clears phone field on click
    private void UsernameMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_UsernameMouseClicked
    {//GEN-HEADEREND:event_UsernameMouseClicked
        Username.setText("");
    }//GEN-LAST:event_UsernameMouseClicked
    // Clears phone field on click
    private void PasswordMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_PasswordMouseClicked
    {//GEN-HEADEREND:event_PasswordMouseClicked
        Password.setText("");
    }//GEN-LAST:event_PasswordMouseClicked
    // Login button logic
    private void LoginBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LoginBActionPerformed
    {//GEN-HEADEREND:event_LoginBActionPerformed
        // Get input from text fields
        PhoneOut = Phone.getText();
        UsernameOut = Username.getText();
        PasswordOut = Password.getText();
        
        LMobj.loginUser();      // Performs user validation
        LMobj.returnLoginStatus();      // Returns message string for success/failure
        
        // If login failed, show error message
        if(LMobj.loginUser() == false)
        {
            errorDisplay.setText(LMobj.returnLoginStatus());
        }
    }//GEN-LAST:event_LoginBActionPerformed
    
// Back button logic: opens the StartPage form
    private void BackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BackActionPerformed
    {//GEN-HEADEREND:event_BackActionPerformed
        Spobj.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    // Getter method for Username input
    public static String getUsernameOut()  
    {
        return UsernameOut;
    }
    
    // Getter method for Phone input
    public static String getPhoneOut()
    {
        return PhoneOut;
    }

    // Getter method for Password input
    public static String getPasswordOut()
    {
        return PasswordOut;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton LoginB;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Username;
    private javax.swing.JTextArea errorDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
